name: CI

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  cd:
    name: CD
    runs-on: ubuntu-latest
    concurrency: cd-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
  
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install Packages
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm exec prisma generate

      - name: Lint
        run: pnpm run ci:lint

        - name: Build
        run: pnpm run ci:build

      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: '${{ secrets.SFTP_USERNAME }}'
          server: '${{ secrets.SFTP_SERVER }}'
          port: '${{ secrets.SFTP_PORT }}'
          ssh_private_key: ${{ secrets.SFTP_PRIVKEY }} 
          local_path: './build/*'
          remote_path: '/var/www/cshs.brmhs.org'

